[project]
name = "audio-to-text"
version = "0.1.0"
description = ""
readme = "README.md"
authors = [
    { name = "Michael Kingston", email = "71872141+mkingopng@users.noreply.github.com" },
]
requires-python = ">=3.12"
dependencies = [
    "mlx-whisper>=0.4.3",
    "pyannote-audio>=4.0.7",
    "python-dotenv>=1.2.2",
    "scipy>=1.18.0",
    "tqdm>=4.66",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
